#!/bin/bash
# Plot Coulomb stress change (CMB_Fix) distribution on the receiving fault plane.
#
# Pipeline:
#   1. Read output/gmt_coulomb.xyz (generated by consolidate.py)
#   2. Convert (lon, lat, depth) → (along-strike distance, depth)
#   3. Render a fault-plane cross-section with GMT 6 (classic mode)
#
# Usage:
#   ./src/plot_coulomb.sh
#   CMB_MIN=-5000 CMB_MAX=5000 ./src/plot_coulomb.sh   # custom colour range
#
# Dependencies: GMT 6, Python 3 + pyproj

set -euo pipefail

# Resolve project root and the Python interpreter path (matches run.sh).
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PYTHON_BIN="/home/sunset/miniconda3/envs/deltacfs/bin/python3"

INPUT="$PROJECT_DIR/output/gmt_coulomb.xyz"
PS="$PROJECT_DIR/output/coulomb_fault_plane.ps"
OUTPUT="$PROJECT_DIR/output/coulomb_fault_plane.pdf"

if [ ! -f "$INPUT" ]; then
  echo "Error: $INPUT not found — run main.py first." >&2
  exit 1
fi

# =========================================================================
# 1. Preprocess — convert (lon,lat,depth) → (strike-dist, depth)
# =========================================================================
eval "$("$PYTHON_BIN" << PYEOF
import os
from collections import defaultdict

# Read depth_step from calculation_setting.dat, then compute the horizontal
# observation spacing.  Must match main.py: observation_distance = depth_step * 2.
with open(os.path.expandvars("$PROJECT_DIR/config/calculation_setting.dat")) as f:
    for line in f:
        if line.strip() and not line.startswith('#'):
            depth_step = float(line.strip().split()[0])
            break
observation_interval = depth_step * 2.0  # km between observation points

with open(os.path.expandvars("$INPUT")) as f:
    raw = [l.split() for l in f if not l.startswith("#") and l.strip()]

by_depth = defaultdict(list)
for lon, lat, depth, cmb, *_ in raw:
    by_depth[float(depth)].append((float(lon), float(lat), float(cmb)))

depths = sorted(by_depth.keys())
all_cmb = [c for pts in by_depth.values() for (_, _, c) in pts]

# Along-strike distance from point index, NOT from geodesic distance.
# The observation points were generated at equal spacing along strike
# (cmp_input.py / geod.fwd), so i * interval is always correct.
n_pts = len(by_depth[depths[0]])
spacing = observation_interval

xyz_path = os.path.expandvars("$PROJECT_DIR/output/fault_plane.xyz")
with open(xyz_path, "w") as out:
    out.write("# dist_along_strike_km  depth_km  CMB_Fix\n")
    for depth in depths:
        pts = by_depth[depth]
        for i, (lon, lat, cmb) in enumerate(pts):
            dist_km = i * spacing
            out.write(f"{dist_km:.4f}  {depth:.1f}  {cmb:.6e}\n")

absmax = max(abs(min(all_cmb)), abs(max(all_cmb)))
print(f"DIST_MAX={(n_pts - 1) * spacing:.1f}")
print(f"DEPTH_MAX={max(depths):.1f}")
print(f"CMB_SYMM={absmax:.2e}")
# Grid spacing for GMT (derived from config, not hardcoded)
print(f"DIST_INC={spacing}")
print(f"DEPTH_INC={depth_step}")
PYEOF
)"

echo "Grid: 0–$DIST_MAX km along strike × 0–$DEPTH_MAX km depth"
echo "CMB_Fix range: ±${CMB_SYMM}"

CMB_MIN="${CMB_MIN:--${CMB_SYMM}}"
CMB_MAX="${CMB_MAX:-${CMB_SYMM}}"

# =========================================================================
# 2. GMT plot (classic mode — avoids psconvert / gs dependency)
# =========================================================================
XYZ="$PROJECT_DIR/output/fault_plane.xyz"
CPT="$PROJECT_DIR/output/.cmb_cpt.$$"
GRD="$PROJECT_DIR/output/.cmb_grd.$$"
cleanup() { rm -f "$CPT" "$GRD" "$XYZ"; }
trap cleanup EXIT

# Diverging CPT centred at 0, symmetrical range
gmt makecpt -Cpolar -T"$CMB_MIN"/"$CMB_MAX"/100 > "$CPT"

# Grid from regular data: grid spacing matches the observation point spacing
gmt xyz2grd "$XYZ" \
  -R0/"$DIST_MAX"/0/"$DEPTH_MAX" \
  -I"${DIST_INC}"/"${DEPTH_INC}" \
  -G"$GRD" 2>/dev/null

# Plot: fault-plane cross-section, depth 0 at top (negative J height flips y)
gmt grdimage "$GRD" -R0/"$DIST_MAX"/0/"$DEPTH_MAX" -JX15c/-9c \
  -C"$CPT" -K \
  -Bxa2f1g2+l"Distance along strike (km)" \
  -Bya1f0.5g1+l"Depth(km)" -BWSen \
  --FONT_ANNOT_PRIMARY=9p --FONT_LABEL=11p \
  --MAP_FRAME_PEN=0.5p \
  --MAP_ANNOT_OFFSET_PRIMARY=2p --MAP_LABEL_OFFSET=6p \
  > "$PS"

# Colour bar on the right side
gmt psscale -C"$CPT" \
  -Dx16c/3c+w8c/0.35c \
  -Bxa5000+l"CMB_Fix (MPa)" \
  -O --FONT_ANNOT_PRIMARY=8p --FONT_LABEL=10p >> "$PS"

echo "Plot written to: $PS"

rm -f "$XYZ"

# Convert to PDF (ghostscript required)
gmt psconvert "$PS" -Tf -P 2>/dev/null && echo "PDF: $OUTPUT"
